[build]
  command = "npm run build" # Adjust this if your build command is different
  publish = "public" # Adjust this to the directory where your static files are built

[functions]
  directory = "netlify/functions" # Directory where your serverless functions are located

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Adjust the function name if needed
  status = 200
